language: rust
cache: cargo
rust:
  - stable
  - beta
before_install:
  - sudo apt-get install libudev-dev
before_script:
  - |
        pip install 'travis-cargo<0.2' --user &&
        export PATH=$HOME/.local/bin:$PATH
script:
  - |
        travis-cargo build &&
        travis-cargo test
after_success:
  - travis-cargo coveralls --no-sudo --verify
